# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('_teste2_rcpp_hello_world', PACKAGE = 'teste2')
}

signC <- function(x, y) {
    .Call('_teste2_signC', PACKAGE = 'teste2', x, y)
}

sumC <- function(x) {
    .Call('_teste2_sumC', PACKAGE = 'teste2', x)
}

add2 <- function(j, k) {
    .Call('_teste2_add2', PACKAGE = 'teste2', j, k)
}

invvech_eigen <- function(x) {
    .Call('_teste2_invvech_eigen', PACKAGE = 'teste2', x)
}

rcppeigen_hello_world <- function() {
    .Call('_teste2_rcppeigen_hello_world', PACKAGE = 'teste2')
}

rcppeigen_bothproducts <- function(x) {
    .Call('_teste2_rcppeigen_bothproducts', PACKAGE = 'teste2', x)
}

functest1 <- function(x) {
    .Call('_teste2_functest1', PACKAGE = 'teste2', x)
}

functest2 <- function(x, i) {
    .Call('_teste2_functest2', PACKAGE = 'teste2', x, i)
}

autos <- function(x) {
    .Call('_teste2_autos', PACKAGE = 'teste2', x)
}

pw <- function(nvar, itera, ncluster, info_j, x, y, z, wi_j_star, wj_star, teta, s, teta0) {
    .Call('_teste2_pw', PACKAGE = 'teste2', nvar, itera, ncluster, info_j, x, y, z, wi_j_star, wj_star, teta, s, teta0)
}

teste_sparse <- function() {
    .Call('_teste2_teste_sparse', PACKAGE = 'teste2')
}

vector_eigen <- function(A, a) {
    .Call('_teste2_vector_eigen', PACKAGE = 'teste2', A, a)
}

diagonalizar <- function(AJ_TETA, SOL_TETA, H_kj, delta) {
    .Call('_teste2_diagonalizar', PACKAGE = 'teste2', AJ_TETA, SOL_TETA, H_kj, delta)
}

diag_eigen <- function(A) {
    .Call('_teste2_diag_eigen', PACKAGE = 'teste2', A)
}

vecto_eigen <- function(A, a) {
    .Call('_teste2_vecto_eigen', PACKAGE = 'teste2', A, a)
}

